disabled_rules:
  - identifier_name
  
opt_in_rules:
  - empty_count
  
excluded:
  - Carthage
  - Pods

line_length:
  warning: 110
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
  error: 200

disabled_rules:
  - trailing_whitespace
